# Generated by Django 5.2.10 on 2026-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_complaint_id_alter_garbagebin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
